import type { Spot } from '@/types'

/**
 * Curated seed dataset (démo). Coordinates are approximate and intended as
 * illustrative starting points; official airspace status is resolved at runtime
 * from the IGN/DGAC layer.
 */
export const SEED_SPOTS: Spot[] = [
  {
    id: 'seed-lille-friche',
    name: 'Friche des Rives du Nord',
    description:
      'Ancien site industriel aux grandes halles ouvertes, idéal pour du freestyle technique à l’abri du vent.',
    city: 'Lille',
    category: 'bando',
    tags: ['halles', 'urbex', 'couvert', 'freestyle'],
    coordinates: { lng: 3.0131, lat: 50.583 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-roubaix-usine',
    name: 'Usine textile désaffectée',
    description: 'Longues nefs en brique, passages en enfilade parfaits pour des lignes rapides.',
    city: 'Roubaix',
    category: 'bando',
    tags: ['industriel', 'brique', 'lignes', 'cinematic'],
    coordinates: { lng: 3.2242, lat: 50.7442 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-opale-bunker',
    name: 'Bunker de la Côte d’Opale',
    description: 'Blockhaus face à la mer, lumière rasante au coucher du soleil. Attention au vent.',
    city: 'Wimereux',
    category: 'cinematic',
    tags: ['mer', 'bunker', 'coucher de soleil', 'mouette'],
    coordinates: { lng: 1.6465, lat: 50.7689 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-vigny-carriere',
    name: 'Carrière de Vigny',
    description: 'Gradins de pierre et plans d’eau, spot ouvert pour du freestyle et du race.',
    city: 'Vigny',
    category: 'freestyle',
    tags: ['carrière', 'hauteur', 'ouvert', 'race'],
    coordinates: { lng: 1.9626, lat: 49.0822 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-poissy-carriere',
    name: 'Carrière des Alluets',
    description: 'Bassin calcaire et falaises accessibles, bon terrain de jeu pour des dives.',
    city: 'Les Alluets-le-Roi',
    category: 'freestyle',
    tags: ['carrière', 'dive', 'falaises'],
    coordinates: { lng: 1.9582, lat: 48.9032 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-paris-parc',
    name: 'Parc naturel du Vexin',
    description: 'Grande plaine dégagée en lisière de forêt, parfait pour s’entraîner au calme.',
    city: 'Vexin français',
    category: 'park',
    tags: ['parc', 'plaine', 'débutant', 'ouvert'],
    coordinates: { lng: 1.7969, lat: 49.1445 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-normandie-viaduc',
    name: 'Point de vue du Viaduc',
    description: 'Vue plongeante sur la vallée, spot cinématique avec de belles trajectoires de descente.',
    city: 'Honfleur',
    category: 'cinematic',
    tags: ['vallée', 'pont', 'vue', 'dive'],
    coordinates: { lng: 0.2427, lat: 49.4212 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-etretat-falaise',
    name: 'Falaises d’Étretat',
    description: 'Arches naturelles célèbres. Voler tôt le matin pour éviter la foule et le vent.',
    city: 'Étretat',
    category: 'cinematic',
    tags: ['falaises', 'mer', 'aérien', 'matin'],
    coordinates: { lng: 0.2385, lat: 49.7076 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-bordeaux-friche',
    name: 'Friche ferroviaire de la Gare',
    description: 'Ancien dépôt SNCF, rails et passerelles métalliques pour des gaps créatifs.',
    city: 'Bordeaux',
    category: 'bando',
    tags: ['rails', 'SNCF', 'métal', 'gaps'],
    coordinates: { lng: -0.4867, lat: 44.8259 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-pilat-dune',
    name: 'Dune du Pilat',
    description: 'Plus haute dune d’Europe. Spot cinématique spectaculaire, respecter les zones protégées.',
    city: 'La Teste-de-Buch',
    category: 'cinematic',
    tags: ['dune', 'mer', 'protégé', 'panorama'],
    coordinates: { lng: -1.2136, lat: 44.6235 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-toulouse-piste',
    name: 'Piste de vitesse toulousaine',
    description: 'Ancien circuit de karting reconverti, lignes de course serrées et portes naturelles.',
    city: 'Toulouse',
    category: 'race',
    tags: ['circuit', 'portes', 'vitesse', 'asphalte'],
    coordinates: { lng: 1.55, lat: 43.6 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-marseille-port',
    name: 'Friche portuaire sud',
    description: 'Entrepôts et grues désaffectés, ambiance industrielle brute pour du bando urbain.',
    city: 'Marseille',
    category: 'bando',
    tags: ['port', 'grues', 'entrepôts', 'urbain'],
    coordinates: { lng: 5.3567, lat: 43.3188 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-lyon-parc',
    name: 'Parc des Berges',
    description: 'Grand parc le long du fleuve, dégagé et accessible, bon pour progresser.',
    city: 'Lyon',
    category: 'park',
    tags: ['parc', 'fleuve', 'accessible', 'progresser'],
    coordinates: { lng: 4.7576, lat: 45.7719 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-grenoble-fort',
    name: 'Fort de la Bastille',
    description: 'Fortifications perchées, vues vertigineuses sur la vallée. Vérifier les zones à proximité.',
    city: 'Grenoble',
    category: 'cinematic',
    tags: ['fort', 'montagne', 'vue', 'histoire'],
    coordinates: { lng: 5.7236, lat: 45.1997 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-millau-viaduc',
    name: 'Belvédère du Viaduc de Millau',
    description: 'Point de vue sur le plus haut viaduc du monde. Espace aérien très contrôlé.',
    city: 'Millau',
    category: 'cinematic',
    tags: ['viaduc', 'panorama', 'contrôlé', 'dive'],
    coordinates: { lng: 3.0226, lat: 44.0804 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'seed-strasbourg-friche',
    name: 'Friche militaire de la Meinau',
    description: 'Bâtiments désaffectés et terrains vagues, bon potentiel pour du freestyle rapproché.',
    city: 'Strasbourg',
    category: 'freestyle',
    tags: ['militaire', 'friche', 'proximité', 'urbex'],
    coordinates: { lng: 7.8034, lat: 48.5551 },
    altitudeCeilingM: null,
    legalStatus: 'unknown',
    source: 'seed',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
]
